apiVersion: v1
kind: Namespace
metadata:
  name: task-pay-api-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-pay-api-deployment
  namespace: task-pay-api-namespace

spec:
  selector:
    matchLabels:
      app: task-pay-api-k8s
  replicas: 4
  template:
    metadata:
      labels:
        app: task-pay-api-k8s
    spec:
      containers:
        - name: task-pay-api-container
          image: task-pay-api-image:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2024
          env: # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: task-pay-api-service
  namespace: task-pay-api-namespace
spec:
  selector:
    app: task-pay-api-k8s
  ports:
    - protocol: TCP
      port: 2024
      targetPort: 2024
  type: NodePort






